// Code generated by "stringer -type=Instruction"; DO NOT EDIT.

package cpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BRK-0]
	_ = x[RTI-64]
	_ = x[JMP_ABS-76]
	_ = x[STA_IND_X-129]
	_ = x[STY_ZP-132]
	_ = x[STA_ZP-133]
	_ = x[STX_ZP-134]
	_ = x[STY_ABS-140]
	_ = x[STA_ABS-141]
	_ = x[STX_ABS-142]
	_ = x[STA_IND_Y-145]
	_ = x[STY_ZP_X-148]
	_ = x[STA_ZP_X-149]
	_ = x[STX_ZP_Y-150]
	_ = x[STA_ABS_Y-153]
	_ = x[STA_ABS_X-157]
	_ = x[LDY_IMM-160]
	_ = x[LDX_IMM-162]
	_ = x[LDY_ZP-164]
	_ = x[LDA_ZP-165]
	_ = x[LDX_ZP-166]
	_ = x[LDA_IMM-169]
	_ = x[LDY_ABS-172]
	_ = x[LDA_ABS-173]
	_ = x[LDX_ABS-174]
	_ = x[NOP-234]
}

const _Instruction_name = "BRKRTIJMP_ABSSTA_IND_XSTY_ZPSTA_ZPSTX_ZPSTY_ABSSTA_ABSSTX_ABSSTA_IND_YSTY_ZP_XSTA_ZP_XSTX_ZP_YSTA_ABS_YSTA_ABS_XLDY_IMMLDX_IMMLDY_ZPLDA_ZPLDX_ZPLDA_IMMLDY_ABSLDA_ABSLDX_ABSNOP"

var _Instruction_map = map[Instruction]string{
	0:   _Instruction_name[0:3],
	64:  _Instruction_name[3:6],
	76:  _Instruction_name[6:13],
	129: _Instruction_name[13:22],
	132: _Instruction_name[22:28],
	133: _Instruction_name[28:34],
	134: _Instruction_name[34:40],
	140: _Instruction_name[40:47],
	141: _Instruction_name[47:54],
	142: _Instruction_name[54:61],
	145: _Instruction_name[61:70],
	148: _Instruction_name[70:78],
	149: _Instruction_name[78:86],
	150: _Instruction_name[86:94],
	153: _Instruction_name[94:103],
	157: _Instruction_name[103:112],
	160: _Instruction_name[112:119],
	162: _Instruction_name[119:126],
	164: _Instruction_name[126:132],
	165: _Instruction_name[132:138],
	166: _Instruction_name[138:144],
	169: _Instruction_name[144:151],
	172: _Instruction_name[151:158],
	173: _Instruction_name[158:165],
	174: _Instruction_name[165:172],
	234: _Instruction_name[172:175],
}

func (i Instruction) String() string {
	if str, ok := _Instruction_map[i]; ok {
		return str
	}
	return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
}
